services:
  - type: web
    name: task-management-app
    env: node
    plan: free
    buildCommand: |
      npm install
      cd frontend && npm install && npm run build
      mkdir -p ../backend/public
      cp -r build/* ../backend/public/
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: mongodb+srv://username:password@cluster.mongodb.net/taskmanagement
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
