services:
  - type: web
    name: task-management-app
    env: node
    plan: free
    buildCommand: |
      cd backend && npm install
      cd ../frontend && npm install && npm run build
      cd ../backend
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        fromDatabase:
          name: taskmanagement
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000

databases:
  - name: taskmanagement
    plan: free
